-keep class com.twinmind.recorder.data.remote.** { *; }
-keep class com.twinmind.recorder.data.local.entity.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn okhttp3.**
-dontwarn retrofit2.**
